version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Resources:/app/Resources
      - ./src:/app/src
    environment:
      - FLASK_ENV=development
    command: python /app/src/app.py
