version: '3'

services:
  web:
    build:
      context: ./src/Frontend  # Ajusta la ruta al directorio de tu frontend
      dockerfile: Dockerfile    # Utiliza el Dockerfile que ya tienes en el directorio frontend
    ports:
      - "3000:3000"  # Mapea el puerto del contenedor al puerto de tu máquina
    depends_on:
      - api

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: form_register
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
    depends_on:
      - db

volumes:
  postgres_data:
